### ISSUE TITLE
Build failing in rpmbuild stage

### ISSUE THREAD

**Issue by jampe** [tabit-pro/qwt-crossbuild#4]
Hi guys

First of all, thanks a lot for this amazing work!

I tried to build the qubes windows tools by executing the commands mentioned in the readme. While executing the rpmbuild command, the build failed for me. The error reported that the output directory of qubes-vmm-xen-windows-pvdrivers can not be found. In the Makefile, this is specified as -o $/qubes-gui-agent-windows-4.0.0/qvideo/miniport/$(OUTDIR)/libxenvchan.dll (changed in 04886eb50478d7fd3333962926cc47cfdbc64ed3). First, I've created the output folder manually, which solved the build command of this dll, however resulted in a linker failure during the compilation of qubes-core-vchan-xen. I was able to solve the problem and build the d by reverting the -o argument of qubes-vmm-xen-windows-pvdrivers to -o $(OUTDIR)/libxenvchan.dll.

Cheers and thanks again for publishing this :-)

**Comment by jevank** [comment]
Nice to hear that it helps and thank you for workaround. Last version qwt-crossbuild is in the [experimental repository](https://github.com/tabit-pro/Qway-qubes-repo/tree/master/qubes-windows-tools) with other our packages. It could be built with [mock](https://github.com/tabit-pro/Qway-qubes-repo/wiki/How-to-build-package-with-mock-in-Qubes-Disposable-VM). This dockerbuild project will be deprecated soon.

**Comment by jampe** [comment]
ahh I've missed the other repository. Can confirm that the build in the Qway-qubes-repo works flawlessly.

Thanks again, - close
